### ISSUE TITLE
vkbottle.exception_factory.error_handler.error_handler:handle:43 - 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by danilmamedov** [profatsky/vk-game-bot#1]
в момент регистрации, когда вводишь ник, выдает ошибку и ничего не сохраняется

![изображение](https://user-images.githubusercontent.com/106846227/171958952-e8be7335-174a-42ae-bd67-af6eee28d2c4.png)

**Comment by profatsky** [comment]
можешь показать что в vk_user заносится на 20 строке, буду очень признателен 

> в момент регистрации, когда вводишь ник, выдает ошибку и ничего не сохраняется
> 
> ![изображение](https://user-images.githubusercontent.com/106846227/171958952-e8be7335-174a-42ae-bd67-af6eee28d2c4.png)

**Comment by danilmamedov** [comment]
эмм, ничего? (я нуб)

![изображение](https://user-images.githubusercontent.com/106846227/172140544-70449a78-c3c5-4235-84d7-05b8cdbd8be6.png)

**Comment by profatsky** [comment]
Если нетрудно, напиши мне, хочется понять из-за чего у тебя ошибка возникает vk.com/profatsky
