### ISSUE TITLE
После выбора цвета кожи - ошибки

### ISSUE THREAD

**Issue by dahasar** [profatsky/vk-game-bot#2]
Скриншот ниже

**Comment by dahasar** [comment]
![Screenshot_2022-06-14-14-47-37-962_com server auditor ssh client](https://user-images.githubusercontent.com/49711854/173570221-f679ea61-44f5-4da8-873b-f2a8ba47ef60.jpg)

**Comment by profatsky** [comment]
К сегодняшнему дню бот полностью исправен, подобных ошибок больше не возникнет
